### ISSUE TITLE
[BUG] AttributeError: 'str' object has no attribute 'exceptions'

### ISSUE THREAD

**Issue by yubiuser** [mborsetti/webchanges#66]
Version 3.17.1, `httpx` installed, `requests` not installed.
Note: a lot of other `304` are handled correctly.

```
2023-12-11 12:13:58,332 handler[140522390620984] INFO: Job 15: https://piunikaweb.com/2022/08/08/google-pixel-6-6-pro-new-updates-bugs-issues-problems-tracker/ started processing (UrlJob)
Traceback (most recent call last):
  File "webchanges/handler.py", line 180, in process
2023-12-11 12:13:58,333 jobs[140522390620984] INFO: Job 15: Sending GET request to https://piunikaweb.com/2022/08/08/google-pixel-6-6-pro-new-updates-bugs-issues-problems-tracker/
2023-12-11 12:13:58,333 jobs[140522390620984] INFO: Job 15: Using the HTTPX HTTP client library with HTTP/2 support
  File "webchanges/jobs.py", line 941, in retrieve
  File "webchanges/jobs.py", line 696, in _retrieve_httpx
webchanges.jobs.NotModifiedError: 304

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "webchanges/handler.py", line 195, in process
  File "webchanges/jobs.py", line 978, in format_error
AttributeError: 'str' object has no attribute 'exceptions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "webchanges.py", line 4, in <module>
  File "webchanges/cli.py", line 375, in main
  File "webchanges/command.py", line 1076, in run
  File "webchanges/main.py", line 98, in run_jobs
  File "webchanges/worker.py", line 211, in run_jobs
  File "webchanges/worker.py", line 87, in job_runner
  File "concurrent/futures/_base.py", line 619, in result_iterator
  File "concurrent/futures/_base.py", line 317, in _result_or_cancel
  File "concurrent/futures/_base.py", line 456, in result
  File "concurrent/futures/_base.py", line 401, in __get_result
  File "concurrent/futures/thread.py", line 58, in run
  File "webchanges/worker.py", line 88, in <lambda>
  File "webchanges/handler.py", line 206, in process
  File "webchanges/jobs.py", line 978, in format_error
AttributeError: 'str' object has no attribute 'exceptions'
[236] Failed to execute script 'webchanges' due to unhandled exception!

```

**Comment by yubiuser** [comment]
Interestingly, running `webchanges --errors` does not error (and results in `200` than `304` http return code).

```
2023-12-11 12:20:58,832 handler[140180533103416] INFO: Job 15: https://piunikaweb.com/2022/08/08/google-pixel-6-6-pro-new-updates-bugs-issues-problems-tracker/ started processing (UrlJob)
2023-12-11 12:20:58,833 jobs[140180533103416] INFO: Job 15: Sending GET request to https://piunikaweb.com/2022/08/08/google-pixel-6-6-pro-new-updates-bugs-issues-problems-tracker/
2023-12-11 12:20:58,833 jobs[140180533103416] INFO: Job 15: Using the HTTPX HTTP client library with HTTP/2 support
....
2023-12-11 12:21:03,305 _client[140180533103416] INFO: HTTP Request: GET https://piunikaweb.com/2023/10/16/google-pixel-6-6-pro-new-updates-bugs-issues-problems-tracker/ "HTTP/2 200 OK"
```

**Comment by mborsetti** [comment]
Thanks and apologies; fixed in 3.17.2.

I did run the tests after manually uninstalling ``requests`` and they now all passed, so hopefully this is the last bug.

Once again, thank you for your patience and for reporting these errors; I learned that legacy testing installing all libraries at once is a problem that needs to be fixed in the future!

PS ``--errors`` ignores all cached content (whose logic leads a website to respond with an [304 Not Modified]) in case it happens to be blank. The logic here can be improved, so thanks for noticing it and reporting it.

**Comment by drws** [comment]
I'm getting this with v3.17.2 and it seems related:

```
AttributeError: 'str' object has no attribute 'Client'

During handling of the above exception, another exception occurred:

AttributeError: 'str' object has no attribute 'RequestError'
```

**Comment by mborsetti** [comment]
Hello @drws,

Thanks for the report and sorry for the issue you have encountered.  

Unfortunately there isn't enough information in your post to debug it and fix it. 

Would you kindly open a [new issue](https://github.com/mborsetti/webchanges/issues/new/choose) providing the full traceback in order to be able to fix it?

**Comment by mborsetti** [comment]
@drws,

Thanks for the report and sorry for the issue.

I _think_ I found the issue even with the limited information, and released version 3.18.  

Could you please check and let me know if this solved your issue?  If not, kindly open a new [bug report](https://github.com/mborsetti/webchanges/issues/new/choose) with the full traceback.

**Comment by drws** [comment]
The bug went away even before upgrade and I was unable to reproduce it again. The same after updating to 3.18 and 3.19. Unfortunately and even with a late answer I don't have any better information. Will open a new issue if something comes up.
